### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by comradekingu** [jesta88/open-battlecry#1]
Noticed this project on Hosted Weblate. There is no license file in the source repo.
MIT is not that great since it requires carrying the actual MIT notice, so it is neither simple to deal with, nor does it give strong protection.
My preference is AGPLv3+, but I haven't contributed yet.

**Comment by jesta88** [comment]
I don't know open source licenses well, I just picked whatever :). I'll actually remove the project from Weblate since it has too many features for my needs, but I'll look at AGPLv3+, thanks!

**Comment by comradekingu** [comment]
Weblate is great though. It is a pain to manage updates to translations otherwise. Also it attracts translators (like me). :)

**Comment by jesta88** [comment]
I'll give it another shot, but it seemed pretty hard to do simple things. It looks like a great tool for complex projects though. All I need is to translate `key value` pairs, like this:

en.txt:
> str_quit Quit
> str_open Open

fr.txt:
> str_quit Quitter
> str_open Ouvrir

etc.

**Comment by comradekingu** [comment]
If you put it in a recognized format that is feasible.
https://docs.weblate.org/en/latest/formats.html
